import './styles.css'
import { defineBoxSkin } from '@/utils/teachingDocument/skins/authoring'

export default defineBoxSkin({
  id: 'builtin.box.note',
  label: '旁注卡',
  description: '仅上下水平规则线、无左右边框的讲义边注式卡片。',
  version: 1,
  printSafe: true,
  className: 'td-skin-box-note',
  tags: ['builtin', 'box'],
  design: {
    tokens: [
      { id: 'builtin.box.note.top-blue', kind: 'color', label: '蓝色顶线', printSafe: true, value: { hex: '#2563EB' } },
      { id: 'builtin.box.note.top-green', kind: 'color', label: '绿色顶线', printSafe: true, value: { hex: '#047857' } },
      { id: 'builtin.box.note.top-amber', kind: 'color', label: '琥珀顶线', printSafe: true, value: { hex: '#B45309' } },
      { id: 'builtin.box.note.top-red', kind: 'color', label: '红色顶线', printSafe: true, value: { hex: '#B91C1C' } },
      { id: 'builtin.box.note.top-purple', kind: 'color', label: '紫色顶线', printSafe: true, value: { hex: '#7C3AED' } },
      { id: 'builtin.box.note.top-teal', kind: 'color', label: '青色顶线', printSafe: true, value: { hex: '#0F766E' } },
      { id: 'builtin.box.note.top-neutral', kind: 'color', label: '中性顶线', printSafe: true, value: { hex: '#3F3F46' } },
      { id: 'builtin.box.note.bottom-hairline', kind: 'color', label: '底部细线', printSafe: true, value: { hex: '#D4D4D8' } },
      { id: 'builtin.box.note.title-blue', kind: 'color', label: '蓝色标题', printSafe: true, value: { hex: '#1E40AF' } },
      { id: 'builtin.box.note.title-green', kind: 'color', label: '绿色标题', printSafe: true, value: { hex: '#065F46' } },
      { id: 'builtin.box.note.title-amber', kind: 'color', label: '琥珀标题', printSafe: true, value: { hex: '#92400E' } },
      { id: 'builtin.box.note.title-red', kind: 'color', label: '红色标题', printSafe: true, value: { hex: '#991B1B' } },
      { id: 'builtin.box.note.title-purple', kind: 'color', label: '紫色标题', printSafe: true, value: { hex: '#6D28D9' } },
      { id: 'builtin.box.note.title-teal', kind: 'color', label: '青色标题', printSafe: true, value: { hex: '#115E59' } },
      { id: 'builtin.box.note.title-neutral', kind: 'color', label: '中性标题', printSafe: true, value: { hex: '#3F3F46' } },
      { id: 'builtin.box.note.top-border-blue', kind: 'border', label: '蓝色顶线边框', printSafe: true, value: { widthPx: 2, style: 'solid', colorTokenId: 'builtin.box.note.top-blue' } },
      { id: 'builtin.box.note.top-border-green', kind: 'border', label: '绿色顶线边框', printSafe: true, value: { widthPx: 2, style: 'solid', colorTokenId: 'builtin.box.note.top-green' } },
      { id: 'builtin.box.note.top-border-amber', kind: 'border', label: '琥珀顶线边框', printSafe: true, value: { widthPx: 2, style: 'solid', colorTokenId: 'builtin.box.note.top-amber' } },
      { id: 'builtin.box.note.top-border-red', kind: 'border', label: '红色顶线边框', printSafe: true, value: { widthPx: 2, style: 'solid', colorTokenId: 'builtin.box.note.top-red' } },
      { id: 'builtin.box.note.top-border-purple', kind: 'border', label: '紫色顶线边框', printSafe: true, value: { widthPx: 2, style: 'solid', colorTokenId: 'builtin.box.note.top-purple' } },
      { id: 'builtin.box.note.top-border-teal', kind: 'border', label: '青色顶线边框', printSafe: true, value: { widthPx: 2, style: 'solid', colorTokenId: 'builtin.box.note.top-teal' } },
      { id: 'builtin.box.note.top-border-neutral', kind: 'border', label: '中性顶线边框', printSafe: true, value: { widthPx: 2, style: 'solid', colorTokenId: 'builtin.box.note.top-neutral' } },
      { id: 'builtin.box.note.bottom-border', kind: 'border', label: '底部细线边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.note.bottom-hairline' } },
    ],
    slots: [
      {
        id: 'topBorder',
        kind: 'border',
        defaultTokenId: 'builtin.box.note.top-border-amber',
        allowedTokenIds: [
          'builtin.box.note.top-border-blue',
          'builtin.box.note.top-border-green',
          'builtin.box.note.top-border-amber',
          'builtin.box.note.top-border-red',
          'builtin.box.note.top-border-purple',
          'builtin.box.note.top-border-teal',
          'builtin.box.note.top-border-neutral',
        ],
      },
      { id: 'bottomBorder', kind: 'border', defaultTokenId: 'builtin.box.note.bottom-border' },
      {
        id: 'titleColor',
        kind: 'color',
        defaultTokenId: 'builtin.box.note.title-amber',
        allowedTokenIds: [
          'builtin.box.note.title-blue',
          'builtin.box.note.title-green',
          'builtin.box.note.title-amber',
          'builtin.box.note.title-red',
          'builtin.box.note.title-purple',
          'builtin.box.note.title-teal',
          'builtin.box.note.title-neutral',
        ],
      },
    ],
    variants: [
      {
        id: 'blue',
        label: '蓝色',
        description: '将旁注卡片切换为蓝色系。',
        tokenBindings: { topBorder: 'builtin.box.note.top-border-blue', titleColor: 'builtin.box.note.title-blue' },
      },
      {
        id: 'green',
        label: '绿色',
        description: '将旁注卡片切换为绿色系。',
        tokenBindings: { topBorder: 'builtin.box.note.top-border-green', titleColor: 'builtin.box.note.title-green' },
      },
      {
        id: 'amber',
        label: '琥珀',
        description: '显式选择琥珀系旁注（与 Base 一致）。',
        tokenBindings: { topBorder: 'builtin.box.note.top-border-amber', titleColor: 'builtin.box.note.title-amber' },
      },
      {
        id: 'red',
        label: '红色',
        description: '将旁注卡片切换为红色系。',
        tokenBindings: { topBorder: 'builtin.box.note.top-border-red', titleColor: 'builtin.box.note.title-red' },
      },
      {
        id: 'purple',
        label: '紫色',
        description: '将旁注卡片切换为紫色系。',
        tokenBindings: { topBorder: 'builtin.box.note.top-border-purple', titleColor: 'builtin.box.note.title-purple' },
      },
      {
        id: 'teal',
        label: '青色',
        description: '将旁注卡片切换为青色系。',
        tokenBindings: { topBorder: 'builtin.box.note.top-border-teal', titleColor: 'builtin.box.note.title-teal' },
      },
      {
        id: 'neutral',
        label: '中性',
        description: '将旁注卡片切换为中性灰。',
        tokenBindings: { topBorder: 'builtin.box.note.top-border-neutral', titleColor: 'builtin.box.note.title-neutral' },
      },
    ],
  },
})
