import './styles.css'
import { defineBoxSkin } from '@/utils/teachingDocument/skins/authoring'

export default defineBoxSkin({
  id: 'builtin.box.soft-fill',
  label: '软填充卡',
  description: '整卡浅色底配同色系浅边框，无深色块的柔和卡片。',
  version: 1,
  printSafe: true,
  className: 'td-skin-box-soft-fill',
  tags: ['builtin', 'box'],
  design: {
    tokens: [
      { id: 'builtin.box.soft-fill.frame-blue', kind: 'color', label: '浅蓝边框', printSafe: true, value: { hex: '#BFDBFE' } },
      { id: 'builtin.box.soft-fill.frame-green', kind: 'color', label: '浅绿边框', printSafe: true, value: { hex: '#A7F3D0' } },
      { id: 'builtin.box.soft-fill.frame-amber', kind: 'color', label: '浅琥珀边框', printSafe: true, value: { hex: '#FDE68A' } },
      { id: 'builtin.box.soft-fill.frame-red', kind: 'color', label: '浅红边框', printSafe: true, value: { hex: '#FECACA' } },
      { id: 'builtin.box.soft-fill.frame-purple', kind: 'color', label: '浅紫边框', printSafe: true, value: { hex: '#DDD6FE' } },
      { id: 'builtin.box.soft-fill.frame-teal', kind: 'color', label: '浅青边框', printSafe: true, value: { hex: '#99F6E4' } },
      { id: 'builtin.box.soft-fill.frame-neutral', kind: 'color', label: '中性边框', printSafe: true, value: { hex: '#E4E4E7' } },
      { id: 'builtin.box.soft-fill.header-blue', kind: 'color', label: '浅蓝标题底', printSafe: true, value: { hex: '#DBEAFE' } },
      { id: 'builtin.box.soft-fill.header-green', kind: 'color', label: '浅绿标题底', printSafe: true, value: { hex: '#D1FAE5' } },
      { id: 'builtin.box.soft-fill.header-amber', kind: 'color', label: '浅琥珀标题底', printSafe: true, value: { hex: '#FEF3C7' } },
      { id: 'builtin.box.soft-fill.header-red', kind: 'color', label: '浅红标题底', printSafe: true, value: { hex: '#FEE2E2' } },
      { id: 'builtin.box.soft-fill.header-purple', kind: 'color', label: '浅紫标题底', printSafe: true, value: { hex: '#EDE9FE' } },
      { id: 'builtin.box.soft-fill.header-teal', kind: 'color', label: '浅青标题底', printSafe: true, value: { hex: '#CCFBF1' } },
      { id: 'builtin.box.soft-fill.header-neutral', kind: 'color', label: '中性标题底', printSafe: true, value: { hex: '#F4F4F5' } },
      { id: 'builtin.box.soft-fill.body-blue', kind: 'color', label: '浅蓝正文底', printSafe: true, value: { hex: '#EFF6FF' } },
      { id: 'builtin.box.soft-fill.body-green', kind: 'color', label: '浅绿正文底', printSafe: true, value: { hex: '#ECFDF5' } },
      { id: 'builtin.box.soft-fill.body-amber', kind: 'color', label: '浅琥珀正文底', printSafe: true, value: { hex: '#FFFBEB' } },
      { id: 'builtin.box.soft-fill.body-red', kind: 'color', label: '浅红正文底', printSafe: true, value: { hex: '#FEF2F2' } },
      { id: 'builtin.box.soft-fill.body-purple', kind: 'color', label: '浅紫正文底', printSafe: true, value: { hex: '#F5F3FF' } },
      { id: 'builtin.box.soft-fill.body-teal', kind: 'color', label: '浅青正文底', printSafe: true, value: { hex: '#F0FDFA' } },
      { id: 'builtin.box.soft-fill.body-neutral', kind: 'color', label: '中性正文底', printSafe: true, value: { hex: '#FAFAFA' } },
      { id: 'builtin.box.soft-fill.title-blue', kind: 'color', label: '蓝色标题', printSafe: true, value: { hex: '#1E40AF' } },
      { id: 'builtin.box.soft-fill.title-green', kind: 'color', label: '绿色标题', printSafe: true, value: { hex: '#065F46' } },
      { id: 'builtin.box.soft-fill.title-amber', kind: 'color', label: '琥珀标题', printSafe: true, value: { hex: '#92400E' } },
      { id: 'builtin.box.soft-fill.title-red', kind: 'color', label: '红色标题', printSafe: true, value: { hex: '#991B1B' } },
      { id: 'builtin.box.soft-fill.title-purple', kind: 'color', label: '紫色标题', printSafe: true, value: { hex: '#6D28D9' } },
      { id: 'builtin.box.soft-fill.title-teal', kind: 'color', label: '青色标题', printSafe: true, value: { hex: '#115E59' } },
      { id: 'builtin.box.soft-fill.title-neutral', kind: 'color', label: '中性标题', printSafe: true, value: { hex: '#3F3F46' } },
      { id: 'builtin.box.soft-fill.frame-border-blue', kind: 'border', label: '浅蓝边框边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.soft-fill.frame-blue' } },
      { id: 'builtin.box.soft-fill.frame-border-green', kind: 'border', label: '浅绿边框边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.soft-fill.frame-green' } },
      { id: 'builtin.box.soft-fill.frame-border-amber', kind: 'border', label: '浅琥珀边框边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.soft-fill.frame-amber' } },
      { id: 'builtin.box.soft-fill.frame-border-red', kind: 'border', label: '浅红边框边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.soft-fill.frame-red' } },
      { id: 'builtin.box.soft-fill.frame-border-purple', kind: 'border', label: '浅紫边框边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.soft-fill.frame-purple' } },
      { id: 'builtin.box.soft-fill.frame-border-teal', kind: 'border', label: '浅青边框边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.soft-fill.frame-teal' } },
      { id: 'builtin.box.soft-fill.frame-border-neutral', kind: 'border', label: '中性边框边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.soft-fill.frame-neutral' } },
    ],
    slots: [
      {
        id: 'frameBorder',
        kind: 'border',
        defaultTokenId: 'builtin.box.soft-fill.frame-border-blue',
        allowedTokenIds: [
          'builtin.box.soft-fill.frame-border-blue',
          'builtin.box.soft-fill.frame-border-green',
          'builtin.box.soft-fill.frame-border-amber',
          'builtin.box.soft-fill.frame-border-red',
          'builtin.box.soft-fill.frame-border-purple',
          'builtin.box.soft-fill.frame-border-teal',
          'builtin.box.soft-fill.frame-border-neutral',
        ],
      },
      {
        id: 'headerFill',
        kind: 'color',
        defaultTokenId: 'builtin.box.soft-fill.header-blue',
        allowedTokenIds: [
          'builtin.box.soft-fill.header-blue',
          'builtin.box.soft-fill.header-green',
          'builtin.box.soft-fill.header-amber',
          'builtin.box.soft-fill.header-red',
          'builtin.box.soft-fill.header-purple',
          'builtin.box.soft-fill.header-teal',
          'builtin.box.soft-fill.header-neutral',
        ],
      },
      {
        id: 'bodyFill',
        kind: 'color',
        defaultTokenId: 'builtin.box.soft-fill.body-blue',
        allowedTokenIds: [
          'builtin.box.soft-fill.body-blue',
          'builtin.box.soft-fill.body-green',
          'builtin.box.soft-fill.body-amber',
          'builtin.box.soft-fill.body-red',
          'builtin.box.soft-fill.body-purple',
          'builtin.box.soft-fill.body-teal',
          'builtin.box.soft-fill.body-neutral',
        ],
      },
      {
        id: 'titleColor',
        kind: 'color',
        defaultTokenId: 'builtin.box.soft-fill.title-blue',
        allowedTokenIds: [
          'builtin.box.soft-fill.title-blue',
          'builtin.box.soft-fill.title-green',
          'builtin.box.soft-fill.title-amber',
          'builtin.box.soft-fill.title-red',
          'builtin.box.soft-fill.title-purple',
          'builtin.box.soft-fill.title-teal',
          'builtin.box.soft-fill.title-neutral',
        ],
      },
    ],
    variants: [
      {
        id: 'blue',
        label: '蓝色',
        description: '显式选择蓝色系软填充（与 Base 一致）。',
        tokenBindings: {
          frameBorder: 'builtin.box.soft-fill.frame-border-blue',
          headerFill: 'builtin.box.soft-fill.header-blue',
          bodyFill: 'builtin.box.soft-fill.body-blue',
          titleColor: 'builtin.box.soft-fill.title-blue',
        },
      },
      {
        id: 'green',
        label: '绿色',
        description: '将软填充卡片切换为绿色系。',
        tokenBindings: {
          frameBorder: 'builtin.box.soft-fill.frame-border-green',
          headerFill: 'builtin.box.soft-fill.header-green',
          bodyFill: 'builtin.box.soft-fill.body-green',
          titleColor: 'builtin.box.soft-fill.title-green',
        },
      },
      {
        id: 'amber',
        label: '琥珀',
        description: '将软填充卡片切换为琥珀色系。',
        tokenBindings: {
          frameBorder: 'builtin.box.soft-fill.frame-border-amber',
          headerFill: 'builtin.box.soft-fill.header-amber',
          bodyFill: 'builtin.box.soft-fill.body-amber',
          titleColor: 'builtin.box.soft-fill.title-amber',
        },
      },
      {
        id: 'red',
        label: '红色',
        description: '将软填充卡片切换为红色系。',
        tokenBindings: {
          frameBorder: 'builtin.box.soft-fill.frame-border-red',
          headerFill: 'builtin.box.soft-fill.header-red',
          bodyFill: 'builtin.box.soft-fill.body-red',
          titleColor: 'builtin.box.soft-fill.title-red',
        },
      },
      {
        id: 'purple',
        label: '紫色',
        description: '将软填充卡片切换为紫色系。',
        tokenBindings: {
          frameBorder: 'builtin.box.soft-fill.frame-border-purple',
          headerFill: 'builtin.box.soft-fill.header-purple',
          bodyFill: 'builtin.box.soft-fill.body-purple',
          titleColor: 'builtin.box.soft-fill.title-purple',
        },
      },
      {
        id: 'teal',
        label: '青色',
        description: '将软填充卡片切换为青色系。',
        tokenBindings: {
          frameBorder: 'builtin.box.soft-fill.frame-border-teal',
          headerFill: 'builtin.box.soft-fill.header-teal',
          bodyFill: 'builtin.box.soft-fill.body-teal',
          titleColor: 'builtin.box.soft-fill.title-teal',
        },
      },
      {
        id: 'neutral',
        label: '中性',
        description: '将软填充卡片切换为中性灰。',
        tokenBindings: {
          frameBorder: 'builtin.box.soft-fill.frame-border-neutral',
          headerFill: 'builtin.box.soft-fill.header-neutral',
          bodyFill: 'builtin.box.soft-fill.body-neutral',
          titleColor: 'builtin.box.soft-fill.title-neutral',
        },
      },
    ],
  },
})
