import './styles.css'
import { defineBoxSkin } from '@/utils/teachingDocument/skins/authoring'

export default defineBoxSkin({
  id: 'builtin.box.outline',
  label: '细线框卡',
  description: '纯线框零填充卡片，标题栏以细分隔线区隔。',
  version: 1,
  printSafe: true,
  className: 'td-skin-box-outline',
  tags: ['builtin', 'box'],
  design: {
    tokens: [
      { id: 'builtin.box.outline.frame-neutral', kind: 'color', label: '中性外框', printSafe: true, value: { hex: '#D4D4D8' } },
      { id: 'builtin.box.outline.frame-blue', kind: 'color', label: '浅蓝外框', printSafe: true, value: { hex: '#BFDBFE' } },
      { id: 'builtin.box.outline.frame-green', kind: 'color', label: '浅绿外框', printSafe: true, value: { hex: '#A7F3D0' } },
      { id: 'builtin.box.outline.frame-amber', kind: 'color', label: '浅琥珀外框', printSafe: true, value: { hex: '#FDE68A' } },
      { id: 'builtin.box.outline.frame-red', kind: 'color', label: '浅红外框', printSafe: true, value: { hex: '#FECACA' } },
      { id: 'builtin.box.outline.frame-purple', kind: 'color', label: '浅紫外框', printSafe: true, value: { hex: '#DDD6FE' } },
      { id: 'builtin.box.outline.frame-teal', kind: 'color', label: '浅青外框', printSafe: true, value: { hex: '#99F6E4' } },
      { id: 'builtin.box.outline.divider-neutral', kind: 'color', label: '中性分隔线', printSafe: true, value: { hex: '#E4E4E7' } },
      { id: 'builtin.box.outline.divider-blue', kind: 'color', label: '浅蓝分隔线', printSafe: true, value: { hex: '#DBEAFE' } },
      { id: 'builtin.box.outline.divider-green', kind: 'color', label: '浅绿分隔线', printSafe: true, value: { hex: '#D1FAE5' } },
      { id: 'builtin.box.outline.divider-amber', kind: 'color', label: '浅琥珀分隔线', printSafe: true, value: { hex: '#FEF3C7' } },
      { id: 'builtin.box.outline.divider-red', kind: 'color', label: '浅红分隔线', printSafe: true, value: { hex: '#FEE2E2' } },
      { id: 'builtin.box.outline.divider-purple', kind: 'color', label: '浅紫分隔线', printSafe: true, value: { hex: '#EDE9FE' } },
      { id: 'builtin.box.outline.divider-teal', kind: 'color', label: '浅青分隔线', printSafe: true, value: { hex: '#CCFBF1' } },
      { id: 'builtin.box.outline.title-neutral', kind: 'color', label: '中性标题', printSafe: true, value: { hex: '#3F3F46' } },
      { id: 'builtin.box.outline.title-blue', kind: 'color', label: '蓝色标题', printSafe: true, value: { hex: '#1E40AF' } },
      { id: 'builtin.box.outline.title-green', kind: 'color', label: '绿色标题', printSafe: true, value: { hex: '#065F46' } },
      { id: 'builtin.box.outline.title-amber', kind: 'color', label: '琥珀标题', printSafe: true, value: { hex: '#92400E' } },
      { id: 'builtin.box.outline.title-red', kind: 'color', label: '红色标题', printSafe: true, value: { hex: '#991B1B' } },
      { id: 'builtin.box.outline.title-purple', kind: 'color', label: '紫色标题', printSafe: true, value: { hex: '#6D28D9' } },
      { id: 'builtin.box.outline.title-teal', kind: 'color', label: '青色标题', printSafe: true, value: { hex: '#115E59' } },
      { id: 'builtin.box.outline.frame-border-neutral', kind: 'border', label: '中性外框边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.outline.frame-neutral' } },
      { id: 'builtin.box.outline.frame-border-blue', kind: 'border', label: '浅蓝外框边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.outline.frame-blue' } },
      { id: 'builtin.box.outline.frame-border-green', kind: 'border', label: '浅绿外框边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.outline.frame-green' } },
      { id: 'builtin.box.outline.frame-border-amber', kind: 'border', label: '浅琥珀外框边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.outline.frame-amber' } },
      { id: 'builtin.box.outline.frame-border-red', kind: 'border', label: '浅红外框边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.outline.frame-red' } },
      { id: 'builtin.box.outline.frame-border-purple', kind: 'border', label: '浅紫外框边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.outline.frame-purple' } },
      { id: 'builtin.box.outline.frame-border-teal', kind: 'border', label: '浅青外框边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.outline.frame-teal' } },
      { id: 'builtin.box.outline.divider-border-neutral', kind: 'border', label: '中性分隔线边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.outline.divider-neutral' } },
      { id: 'builtin.box.outline.divider-border-blue', kind: 'border', label: '浅蓝分隔线边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.outline.divider-blue' } },
      { id: 'builtin.box.outline.divider-border-green', kind: 'border', label: '浅绿分隔线边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.outline.divider-green' } },
      { id: 'builtin.box.outline.divider-border-amber', kind: 'border', label: '浅琥珀分隔线边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.outline.divider-amber' } },
      { id: 'builtin.box.outline.divider-border-red', kind: 'border', label: '浅红分隔线边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.outline.divider-red' } },
      { id: 'builtin.box.outline.divider-border-purple', kind: 'border', label: '浅紫分隔线边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.outline.divider-purple' } },
      { id: 'builtin.box.outline.divider-border-teal', kind: 'border', label: '浅青分隔线边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.outline.divider-teal' } },
    ],
    slots: [
      {
        id: 'frameBorder',
        kind: 'border',
        defaultTokenId: 'builtin.box.outline.frame-border-neutral',
        allowedTokenIds: [
          'builtin.box.outline.frame-border-neutral',
          'builtin.box.outline.frame-border-blue',
          'builtin.box.outline.frame-border-green',
          'builtin.box.outline.frame-border-amber',
          'builtin.box.outline.frame-border-red',
          'builtin.box.outline.frame-border-purple',
          'builtin.box.outline.frame-border-teal',
        ],
      },
      {
        id: 'dividerBorder',
        kind: 'border',
        defaultTokenId: 'builtin.box.outline.divider-border-neutral',
        allowedTokenIds: [
          'builtin.box.outline.divider-border-neutral',
          'builtin.box.outline.divider-border-blue',
          'builtin.box.outline.divider-border-green',
          'builtin.box.outline.divider-border-amber',
          'builtin.box.outline.divider-border-red',
          'builtin.box.outline.divider-border-purple',
          'builtin.box.outline.divider-border-teal',
        ],
      },
      {
        id: 'titleColor',
        kind: 'color',
        defaultTokenId: 'builtin.box.outline.title-neutral',
        allowedTokenIds: [
          'builtin.box.outline.title-neutral',
          'builtin.box.outline.title-blue',
          'builtin.box.outline.title-green',
          'builtin.box.outline.title-amber',
          'builtin.box.outline.title-red',
          'builtin.box.outline.title-purple',
          'builtin.box.outline.title-teal',
        ],
      },
    ],
    variants: [
      {
        id: 'neutral',
        label: '中性',
        description: '显式选择中性灰线框（与 Base 一致）。',
        tokenBindings: {
          frameBorder: 'builtin.box.outline.frame-border-neutral',
          dividerBorder: 'builtin.box.outline.divider-border-neutral',
          titleColor: 'builtin.box.outline.title-neutral',
        },
      },
      {
        id: 'blue',
        label: '蓝色',
        description: '将线框卡片切换为蓝色系。',
        tokenBindings: {
          frameBorder: 'builtin.box.outline.frame-border-blue',
          dividerBorder: 'builtin.box.outline.divider-border-blue',
          titleColor: 'builtin.box.outline.title-blue',
        },
      },
      {
        id: 'green',
        label: '绿色',
        description: '将线框卡片切换为绿色系。',
        tokenBindings: {
          frameBorder: 'builtin.box.outline.frame-border-green',
          dividerBorder: 'builtin.box.outline.divider-border-green',
          titleColor: 'builtin.box.outline.title-green',
        },
      },
      {
        id: 'amber',
        label: '琥珀',
        description: '将线框卡片切换为琥珀色系。',
        tokenBindings: {
          frameBorder: 'builtin.box.outline.frame-border-amber',
          dividerBorder: 'builtin.box.outline.divider-border-amber',
          titleColor: 'builtin.box.outline.title-amber',
        },
      },
      {
        id: 'red',
        label: '红色',
        description: '将线框卡片切换为红色系。',
        tokenBindings: {
          frameBorder: 'builtin.box.outline.frame-border-red',
          dividerBorder: 'builtin.box.outline.divider-border-red',
          titleColor: 'builtin.box.outline.title-red',
        },
      },
      {
        id: 'purple',
        label: '紫色',
        description: '将线框卡片切换为紫色系。',
        tokenBindings: {
          frameBorder: 'builtin.box.outline.frame-border-purple',
          dividerBorder: 'builtin.box.outline.divider-border-purple',
          titleColor: 'builtin.box.outline.title-purple',
        },
      },
      {
        id: 'teal',
        label: '青色',
        description: '将线框卡片切换为青色系。',
        tokenBindings: {
          frameBorder: 'builtin.box.outline.frame-border-teal',
          dividerBorder: 'builtin.box.outline.divider-border-teal',
          titleColor: 'builtin.box.outline.title-teal',
        },
      },
    ],
  },
})
