import { useEffect,useState } from 'react'
import { useNavigate,useParams } from 'react-router-dom'
import { AlertCircle,ArrowLeft,Download,RefreshCw,ZoomIn,ZoomOut } from 'lucide-react'
import { layoutDraftsApi,type LayoutDraft } from '@/api/layoutDrafts'
export default function LayoutDraftPreviewPage(){
 const {draftId=''}=useParams();const navigate=useNavigate();const [draft,setDraft]=useState<LayoutDraft|null>(null);const [error,setError]=useState('');const [zoom,setZoom]=useState(80);const [busy,setBusy]=useState(false);const [variant,setVariant]=useState<'student'|'teacher'>('student')
 const load=()=>layoutDraftsApi.get(draftId).then(r=>{setDraft(r.draft);setError('')}).catch(e=>setError(e instanceof Error?e.message:String(e)))
 useEffect(()=>{load()},[draftId])
 useEffect(()=>{if(!draft||!['queued','rendering'].includes(draft.preview.status))return;const timer=window.setInterval(load,750);return()=>window.clearInterval(timer)},[draft?.preview.status,draftId])
 async function preview(){if(!draft)return;setBusy(true);try{const synced=await layoutDraftsApi.refreshContent(draft.id,draft.revision);const response=await layoutDraftsApi.preview(synced.draft.id,synced.draft.revision);setDraft({...synced.draft,preview:response.preview});setError('')}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function exportPdf(){if(!draft)return;setBusy(true);try{const r=await layoutDraftsApi.export(draft.id,draft.revision);if(r.url)window.open(r.url,'_blank')}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 const realtime=(()=>{if(!draft)return null;try{return JSON.parse(sessionStorage.getItem(`layout-realtime:${draft.id}:r${draft.revision}`)||'null') as {variant:'student'|'teacher';result:{pages:number;questionMeasurements:Array<{questionNo:string;startPage:number}>}}|null}catch{return null}})()
 useEffect(()=>{if(realtime?.variant)setVariant(realtime.variant)},[draft?.id,draft?.revision])
 const variantPreview=draft?.preview.variants?.[variant];const shown=variantPreview&&(variantPreview.pdfUrl||variantPreview.pageImages.length)?variantPreview:draft?.preview
 const comparison=realtime&&realtime.variant===variant&&shown?.pageCount?compareRealtimePreview(realtime.result,shown.pageCount,draft?.preview.warnings.filter(w=>(!w.variant||w.variant===variant))||[]):[]
 return <div className="space-y-4"><div className="flex items-center justify-between"><div><button className="mb-2 inline-flex items-center gap-1 text-xs text-zinc-500" onClick={()=>navigate('/questions/basket')}><ArrowLeft className="size-3.5"/>返回试题篮</button><h1 className="text-lg font-semibold">{draft?.name||'精确预览'}</h1><p className="text-xs text-zinc-500">版本 {draft?.revision||'-'} · 同步生成学生版与教师版 · 精确预览由最终导出引擎生成</p></div><div className="flex gap-2"><div className="flex rounded-md border bg-zinc-100 p-0.5 dark:bg-zinc-900" role="tablist" aria-label="预览版本"><button className={`rounded px-3 py-1.5 text-xs ${variant==='student'?'bg-white font-medium shadow-sm dark:bg-zinc-800':''}`} onClick={()=>setVariant('student')}>学生版</button><button className={`rounded px-3 py-1.5 text-xs ${variant==='teacher'?'bg-white font-medium shadow-sm dark:bg-zinc-800':''}`} onClick={()=>setVariant('teacher')}>教师版</button></div><button className="rounded-md border px-3 py-2 text-xs" title="缩小" onClick={()=>setZoom(Math.max(40,zoom-10))}><ZoomOut className="size-4"/></button><button className="rounded-md border px-3 py-2 text-xs" title="放大" onClick={()=>setZoom(Math.min(140,zoom+10))}><ZoomIn className="size-4"/></button><button disabled={busy} className="inline-flex items-center gap-2 rounded-md border px-3 py-2 text-xs" onClick={preview}><RefreshCw className={`size-4 ${busy?'animate-spin':''}`}/>生成预览</button><button disabled={busy||!draft} className="inline-flex items-center gap-2 rounded-md bg-zinc-950 px-3 py-2 text-xs text-white dark:bg-zinc-100 dark:text-zinc-950" onClick={exportPdf}><Download className="size-4"/>最终导出</button></div></div>
 {error?<div className="flex gap-2 rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700"><AlertCircle className="size-4 shrink-0"/>{error}</div>:null}
 {draft?.preview.error?<div className="rounded-md border p-3 text-sm">{draft.preview.error}<button className="ml-3 underline" onClick={preview}>重试</button></div>:null}
 {comparison.length?<section className="border border-blue-200 bg-blue-50 p-3 text-xs text-blue-900"><b>实时预览与精确预览存在差异</b><div className="mt-1 space-y-1">{comparison.map((message,index)=><p key={index}>{message}</p>)}</div></section>:null}
 {draft?.preview.warnings.filter(w=>!w.variant||w.variant===variant).length?<section className="border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900"><b>排版诊断（{draft.preview.warnings.filter(w=>!w.variant||w.variant===variant).length}）</b><div className="mt-2 space-y-1">{draft.preview.warnings.filter(w=>!w.variant||w.variant===variant).map((warning,index)=><button key={`${warning.code}-${warning.questionId}-${index}`} className="block w-full text-left hover:underline" onClick={()=>warning.page&&document.getElementById(`preview-page-${warning.page}`)?.scrollIntoView({behavior:'smooth',block:'start'})}>{warning.questionNo?`第 ${warning.questionNo} 题 · `:''}{warning.page?`第 ${warning.page} 页 · `:''}{warning.message}{warning.suggestion?` 建议：${warning.suggestion}`:''}</button>)}</div></section>:null}
 <div className="min-h-[60vh] overflow-auto rounded-lg border bg-zinc-100 p-6 dark:bg-zinc-950">{shown?.pageImages.length?shown.pageImages.map((src,i)=><div id={`preview-page-${i+1}`} key={src} className="scroll-mt-4"><img src={src} alt={`${variant==='teacher'?'教师版':'学生版'}第 ${i+1} 页`} className="mx-auto mb-6 shadow-sm" style={{width:`${zoom}%`}}/></div>):shown?.pdfUrl?<iframe title={`${variant==='teacher'?'教师版':'学生版'} PDF 预览`} src={shown.pdfUrl} className="h-[75vh] w-full bg-white"/>:<div className="flex h-80 items-center justify-center text-sm text-zinc-500">{busy||draft?.preview.status==='queued'||draft?.preview.status==='rendering'?'正在编译学生版与教师版预览…':'尚未生成预览'}</div>}</div></div>
}

function compareRealtimePreview(realtime:{pages:number;questionMeasurements:Array<{questionNo:string;startPage:number}>},pdfPages:number,warnings:Array<{questionNo?:string;page?:number}>){const messages:string[]=[];if(realtime.pages!==pdfPages)messages.push(`总页数：实时预览 ${realtime.pages} 页，精确预览 ${pdfPages} 页。`);const starts=new Map(realtime.questionMeasurements.map(item=>[item.questionNo,item.startPage]));for(const warning of warnings){if(warning.questionNo&&warning.page&&starts.has(warning.questionNo)&&starts.get(warning.questionNo)!==warning.page)messages.push(`第 ${warning.questionNo} 题：实时预览从第 ${starts.get(warning.questionNo)} 页开始，精确诊断位于第 ${warning.page} 页。`)}return Array.from(new Set(messages)).slice(0,6)}
