import { useEffect,useMemo,useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Clock3,Eye,FilePlus2,LayoutTemplate,Pencil,Search,Trash2 } from 'lucide-react'
import { collectionsApi } from '@/api/collections'
import { layoutDraftsApi,type LayoutDraft } from '@/api/layoutDrafts'
import type { CollectionSummary } from '@/types'

const button='inline-flex h-9 items-center justify-center gap-2 rounded-md border border-zinc-200 bg-white px-3 text-sm font-medium text-zinc-700 hover:bg-zinc-50 disabled:opacity-40 dark:border-zinc-800 dark:bg-zinc-950 dark:text-zinc-300 dark:hover:bg-zinc-900'
const statusStyle:Record<string,string>={ready:'border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-900/50 dark:bg-emerald-950/20 dark:text-emerald-400',failed:'border-red-200 bg-red-50 text-red-700 dark:border-red-900/50 dark:bg-red-950/20 dark:text-red-400',queued:'border-amber-200 bg-amber-50 text-amber-700 dark:border-amber-900/50 dark:bg-amber-950/20 dark:text-amber-400',rendering:'border-amber-200 bg-amber-50 text-amber-700 dark:border-amber-900/50 dark:bg-amber-950/20 dark:text-amber-400',idle:'border-zinc-200 bg-zinc-100 text-zinc-600 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-300'}
const statusLabel:Record<string,string>={ready:'预览就绪',failed:'预览失败',queued:'等待编译',rendering:'正在编译',idle:'未生成预览'}

export default function LayoutDraftsPage(){
 const navigate=useNavigate();const [items,setItems]=useState<LayoutDraft[]>([]);const [collections,setCollections]=useState<CollectionSummary[]>([]);const [q,setQ]=useState('');const [collectionId,setCollectionId]=useState('');const [status,setStatus]=useState('');const [page,setPage]=useState(1);const [total,setTotal]=useState(0);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const pageSize=15
 async function load(){setLoading(true);try{const [drafts,groups]=await Promise.all([layoutDraftsApi.search({q,collectionId,status,page,pageSize}),collectionsApi.listCollections()]);setItems(drafts.items);setTotal(drafts.total);setCollections(groups.items);setError('')}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}}
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),q?250:0);return()=>clearTimeout(timer)},[q,collectionId,status,page])
 const pages=Math.max(1,Math.ceil(total/pageSize));const collectionOptions=useMemo(()=>collections.filter((item)=>item.questionCount>0),[collections])
 async function createDraft(){const target=collectionId||collectionOptions[0]?.id;if(!target)return;const response=await layoutDraftsApi.create(target,{});navigate(`/questions/collections/${encodeURIComponent(target)}/layout-drafts/${encodeURIComponent(response.draftId)}`)}
 async function rename(draft:LayoutDraft){const name=window.prompt('输入新的草稿名称',draft.name)?.trim();if(!name||name===draft.name)return;await layoutDraftsApi.save(draft.id,{revision:draft.revision,layout:draft.layout,name});await load()}
 async function remove(draft:LayoutDraft){if(!window.confirm(`确定删除排版草稿“${draft.name}”？相关预览文件也会一并删除。`))return;await layoutDraftsApi.remove(draft.id);await load()}
 return <section className="min-h-[calc(100vh-6rem)] space-y-6 bg-zinc-50/30 p-6 text-zinc-900 dark:bg-zinc-950 dark:text-zinc-50">
  <div className="flex flex-col gap-4 border-b border-zinc-200 pb-5 dark:border-zinc-800 md:flex-row md:items-end md:justify-between"><div><p className="text-[13px] font-medium text-zinc-500">题库 / 排版草稿</p><h1 className="mt-1 text-2xl font-semibold">排版草稿</h1><p className="mt-1 text-[13px] text-zinc-500">管理保存的试卷内容快照、布局版本和精确预览。</p></div><button className="inline-flex h-9 items-center gap-2 rounded-md bg-zinc-900 px-4 text-sm font-medium text-white dark:bg-zinc-50 dark:text-zinc-900" onClick={()=>void createDraft()} disabled={!collectionOptions.length}><FilePlus2 className="size-4"/>新建排版草稿</button></div>
  <div className="grid gap-3 rounded-lg border border-zinc-200 bg-white p-4 shadow-sm dark:border-zinc-800 dark:bg-zinc-950 md:grid-cols-[minmax(240px,1fr)_220px_180px]"><label className="relative"><Search className="absolute left-3 top-2.5 size-4 text-zinc-400"/><input className="h-9 w-full rounded-md border border-zinc-200 pl-9 pr-3 text-sm dark:border-zinc-800 dark:bg-zinc-950" placeholder="搜索草稿或试卷名称" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/></label><select className="h-9 rounded-md border border-zinc-200 bg-white px-3 text-sm dark:border-zinc-800 dark:bg-zinc-950" value={collectionId} onChange={e=>{setCollectionId(e.target.value);setPage(1)}}><option value="">全部试卷篮</option>{collections.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select><select className="h-9 rounded-md border border-zinc-200 bg-white px-3 text-sm dark:border-zinc-800 dark:bg-zinc-950" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">全部状态</option>{Object.entries(statusLabel).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>
  {error?<div className="border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>:null}
  <div className="overflow-hidden rounded-lg border border-zinc-200 bg-white shadow-sm dark:border-zinc-800 dark:bg-zinc-950"><div className="grid grid-cols-[minmax(260px,1.5fr)_minmax(180px,1fr)_120px_100px_160px] border-b border-zinc-200 bg-zinc-50/70 px-4 text-xs font-semibold text-zinc-500 dark:border-zinc-800 dark:bg-zinc-900/40"><span className="py-3">草稿</span><span className="py-3">所属试卷篮</span><span className="py-3">状态</span><span className="py-3">版本</span><span className="py-3 text-right">操作</span></div>{loading?<div className="p-10 text-center text-sm text-zinc-500">正在读取草稿...</div>:items.length?items.map(draft=><div key={draft.id} className="grid grid-cols-[minmax(260px,1.5fr)_minmax(180px,1fr)_120px_100px_160px] items-center border-b border-zinc-100 px-4 last:border-0 hover:bg-zinc-50/50 dark:border-zinc-900 dark:hover:bg-zinc-900/30"><div className="min-w-0 py-3"><button className="truncate text-left text-sm font-medium hover:underline" onClick={()=>navigate(`/questions/collections/${draft.collectionId}/layout-drafts/${draft.id}`)}>{draft.name}</button><p className="mt-1 flex items-center gap-1 text-xs text-zinc-500"><Clock3 className="size-3"/>{new Date(draft.updatedAt).toLocaleString()}</p></div><span className="truncate py-3 text-sm text-zinc-600 dark:text-zinc-300">{draft.collectionTitle||draft.collectionId}</span><span><span className={`inline-flex rounded-md border px-2 py-0.5 text-[11px] font-medium ${statusStyle[draft.preview.status]||statusStyle.idle}`}>{statusLabel[draft.preview.status]||draft.preview.status}</span></span><span className="font-mono text-xs text-zinc-500">r{draft.revision}</span><div className="flex justify-end gap-1"><button className="rounded-md p-2 text-zinc-500 hover:bg-zinc-100" title="打开工作台" onClick={()=>navigate(`/questions/collections/${draft.collectionId}/layout-drafts/${draft.id}`)}><LayoutTemplate className="size-4"/></button><button className="rounded-md p-2 text-zinc-500 hover:bg-zinc-100" title="精确预览" onClick={()=>navigate(`/questions/layout-drafts/${draft.id}/preview`)}><Eye className="size-4"/></button><button className="rounded-md p-2 text-zinc-500 hover:bg-zinc-100" title="重命名" onClick={()=>void rename(draft)}><Pencil className="size-4"/></button><button className="rounded-md p-2 text-red-600 hover:bg-red-50" title="删除" onClick={()=>void remove(draft)}><Trash2 className="size-4"/></button></div></div>):<div className="p-12 text-center"><LayoutTemplate className="mx-auto size-8 text-zinc-300"/><p className="mt-3 text-sm font-medium">暂无匹配的排版草稿</p><p className="mt-1 text-xs text-zinc-500">从试卷篮创建草稿后会显示在这里。</p></div>}</div>
  <div className="flex items-center justify-between text-xs text-zinc-500"><span>共 {total} 份草稿</span><div className="flex gap-2"><button className={button} disabled={page<=1} onClick={()=>setPage(page-1)}>上一页</button><span className="flex h-9 items-center px-2">{page} / {pages}</span><button className={button} disabled={page>=pages} onClick={()=>setPage(page+1)}>下一页</button></div></div>
 </section>
}
