import './styles.css'
import { defineBoxSkin } from '@/utils/teachingDocument/skins/authoring'

export default defineBoxSkin({
  id: 'builtin.box.trap-alert',
  label: '错因警示框',
  description: '高反差警戒边框与柔和底色，专用于易错点辨析与避坑指南。',
  version: 1,
  printSafe: true,
  className: 'td-skin-box-trap-alert',
  supportedTemplates: ['warning', 'concept', 'plain'],
  tags: ['builtin', 'box'],
  design: {
    tokens: [
      { id: 'builtin.box.trap-alert.accent-red', kind: 'color', label: '红色强调线', printSafe: true, value: { hex: '#EF4444' } },
      { id: 'builtin.box.trap-alert.accent-amber', kind: 'color', label: '琥珀强调线', printSafe: true, value: { hex: '#B45309' } },
      { id: 'builtin.box.trap-alert.accent-blue', kind: 'color', label: '蓝色强调线', printSafe: true, value: { hex: '#2563EB' } },
      { id: 'builtin.box.trap-alert.accent-green', kind: 'color', label: '绿色强调线', printSafe: true, value: { hex: '#047857' } },
      { id: 'builtin.box.trap-alert.accent-purple', kind: 'color', label: '紫色强调线', printSafe: true, value: { hex: '#7C3AED' } },
      { id: 'builtin.box.trap-alert.accent-teal', kind: 'color', label: '青色强调线', printSafe: true, value: { hex: '#0F766E' } },
      { id: 'builtin.box.trap-alert.accent-neutral', kind: 'color', label: '中性强调线', printSafe: true, value: { hex: '#3F3F46' } },

      { id: 'builtin.box.trap-alert.border-red', kind: 'color', label: '浅红边框', printSafe: true, value: { hex: '#FECACA' } },
      { id: 'builtin.box.trap-alert.border-amber', kind: 'color', label: '浅琥珀边框', printSafe: true, value: { hex: '#FDE68A' } },
      { id: 'builtin.box.trap-alert.border-blue', kind: 'color', label: '浅蓝边框', printSafe: true, value: { hex: '#BFDBFE' } },
      { id: 'builtin.box.trap-alert.border-green', kind: 'color', label: '浅绿边框', printSafe: true, value: { hex: '#A7F3D0' } },
      { id: 'builtin.box.trap-alert.border-purple', kind: 'color', label: '浅紫边框', printSafe: true, value: { hex: '#DDD6FE' } },
      { id: 'builtin.box.trap-alert.border-teal', kind: 'color', label: '浅青边框', printSafe: true, value: { hex: '#99F6E4' } },
      { id: 'builtin.box.trap-alert.border-neutral', kind: 'color', label: '中性边框', printSafe: true, value: { hex: '#D4D4D8' } },

      { id: 'builtin.box.trap-alert.header-red', kind: 'color', label: '浅红标题背景', printSafe: true, value: { hex: '#FEE2E2' } },
      { id: 'builtin.box.trap-alert.header-amber', kind: 'color', label: '浅琥珀标题背景', printSafe: true, value: { hex: '#FEF3C7' } },
      { id: 'builtin.box.trap-alert.header-blue', kind: 'color', label: '浅蓝标题背景', printSafe: true, value: { hex: '#DBEAFE' } },
      { id: 'builtin.box.trap-alert.header-green', kind: 'color', label: '浅绿标题背景', printSafe: true, value: { hex: '#D1FAE5' } },
      { id: 'builtin.box.trap-alert.header-purple', kind: 'color', label: '浅紫标题背景', printSafe: true, value: { hex: '#EDE9FE' } },
      { id: 'builtin.box.trap-alert.header-teal', kind: 'color', label: '浅青标题背景', printSafe: true, value: { hex: '#CCFBF1' } },
      { id: 'builtin.box.trap-alert.header-neutral', kind: 'color', label: '中性标题背景', printSafe: true, value: { hex: '#F4F4F5' } },

      { id: 'builtin.box.trap-alert.body-red', kind: 'color', label: '浅红正文背景', printSafe: true, value: { hex: '#FEF2F2' } },
      { id: 'builtin.box.trap-alert.body-amber', kind: 'color', label: '浅琥珀正文背景', printSafe: true, value: { hex: '#FFFBEB' } },
      { id: 'builtin.box.trap-alert.body-blue', kind: 'color', label: '浅蓝正文背景', printSafe: true, value: { hex: '#EFF6FF' } },
      { id: 'builtin.box.trap-alert.body-green', kind: 'color', label: '浅绿正文背景', printSafe: true, value: { hex: '#ECFDF5' } },
      { id: 'builtin.box.trap-alert.body-purple', kind: 'color', label: '浅紫正文背景', printSafe: true, value: { hex: '#F5F3FF' } },
      { id: 'builtin.box.trap-alert.body-teal', kind: 'color', label: '浅青正文背景', printSafe: true, value: { hex: '#F0FDFA' } },
      { id: 'builtin.box.trap-alert.body-neutral', kind: 'color', label: '中性正文背景', printSafe: true, value: { hex: '#FAFAFA' } },

      { id: 'builtin.box.trap-alert.frame-red', kind: 'border', label: '浅红边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.trap-alert.border-red' } },
      { id: 'builtin.box.trap-alert.frame-amber', kind: 'border', label: '浅琥珀边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.trap-alert.border-amber' } },
      { id: 'builtin.box.trap-alert.frame-blue', kind: 'border', label: '浅蓝边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.trap-alert.border-blue' } },
      { id: 'builtin.box.trap-alert.frame-green', kind: 'border', label: '浅绿边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.trap-alert.border-green' } },
      { id: 'builtin.box.trap-alert.frame-purple', kind: 'border', label: '浅紫边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.trap-alert.border-purple' } },
      { id: 'builtin.box.trap-alert.frame-teal', kind: 'border', label: '浅青边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.trap-alert.border-teal' } },
      { id: 'builtin.box.trap-alert.frame-neutral', kind: 'border', label: '中性边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.trap-alert.border-neutral' } },
    ],
    slots: [
      {
        id: 'accentColor',
        kind: 'color',
        defaultTokenId: 'builtin.box.trap-alert.accent-red',
        allowedTokenIds: [
          'builtin.box.trap-alert.accent-red',
          'builtin.box.trap-alert.accent-amber',
          'builtin.box.trap-alert.accent-blue',
          'builtin.box.trap-alert.accent-green',
          'builtin.box.trap-alert.accent-purple',
          'builtin.box.trap-alert.accent-teal',
          'builtin.box.trap-alert.accent-neutral',
        ],
      },
      {
        id: 'frameBorder',
        kind: 'border',
        defaultTokenId: 'builtin.box.trap-alert.frame-red',
        allowedTokenIds: [
          'builtin.box.trap-alert.frame-red',
          'builtin.box.trap-alert.frame-amber',
          'builtin.box.trap-alert.frame-blue',
          'builtin.box.trap-alert.frame-green',
          'builtin.box.trap-alert.frame-purple',
          'builtin.box.trap-alert.frame-teal',
          'builtin.box.trap-alert.frame-neutral',
        ],
      },
      {
        id: 'headerFill',
        kind: 'color',
        defaultTokenId: 'builtin.box.trap-alert.header-red',
        allowedTokenIds: [
          'builtin.box.trap-alert.header-red',
          'builtin.box.trap-alert.header-amber',
          'builtin.box.trap-alert.header-blue',
          'builtin.box.trap-alert.header-green',
          'builtin.box.trap-alert.header-purple',
          'builtin.box.trap-alert.header-teal',
          'builtin.box.trap-alert.header-neutral',
        ],
      },
      {
        id: 'bodyFill',
        kind: 'color',
        defaultTokenId: 'builtin.box.trap-alert.body-red',
        allowedTokenIds: [
          'builtin.box.trap-alert.body-red',
          'builtin.box.trap-alert.body-amber',
          'builtin.box.trap-alert.body-blue',
          'builtin.box.trap-alert.body-green',
          'builtin.box.trap-alert.body-purple',
          'builtin.box.trap-alert.body-teal',
          'builtin.box.trap-alert.body-neutral',
        ],
      },
    ],
    variants: [
      {
        id: 'red',
        label: '红色',
        description: '切换为红色避坑框。',
        tokenBindings: {
          accentColor: 'builtin.box.trap-alert.accent-red',
          frameBorder: 'builtin.box.trap-alert.frame-red',
          headerFill: 'builtin.box.trap-alert.header-red',
          bodyFill: 'builtin.box.trap-alert.body-red',
        },
      },
      {
        id: 'amber',
        label: '琥珀',
        description: '切换为琥珀色避坑框。',
        tokenBindings: {
          accentColor: 'builtin.box.trap-alert.accent-amber',
          frameBorder: 'builtin.box.trap-alert.frame-amber',
          headerFill: 'builtin.box.trap-alert.header-amber',
          bodyFill: 'builtin.box.trap-alert.body-amber',
        },
      },
      {
        id: 'blue',
        label: '蓝色',
        description: '切换为蓝色避坑框。',
        tokenBindings: {
          accentColor: 'builtin.box.trap-alert.accent-blue',
          frameBorder: 'builtin.box.trap-alert.frame-blue',
          headerFill: 'builtin.box.trap-alert.header-blue',
          bodyFill: 'builtin.box.trap-alert.body-blue',
        },
      },
      {
        id: 'green',
        label: '绿色',
        description: '切换为绿色避坑框。',
        tokenBindings: {
          accentColor: 'builtin.box.trap-alert.accent-green',
          frameBorder: 'builtin.box.trap-alert.frame-green',
          headerFill: 'builtin.box.trap-alert.header-green',
          bodyFill: 'builtin.box.trap-alert.body-green',
        },
      },
      {
        id: 'purple',
        label: '紫色',
        description: '切换为紫色避坑框。',
        tokenBindings: {
          accentColor: 'builtin.box.trap-alert.accent-purple',
          frameBorder: 'builtin.box.trap-alert.frame-purple',
          headerFill: 'builtin.box.trap-alert.header-purple',
          bodyFill: 'builtin.box.trap-alert.body-purple',
        },
      },
      {
        id: 'teal',
        label: '青色',
        description: '切换为青色避坑框。',
        tokenBindings: {
          accentColor: 'builtin.box.trap-alert.accent-teal',
          frameBorder: 'builtin.box.trap-alert.frame-teal',
          headerFill: 'builtin.box.trap-alert.header-teal',
          bodyFill: 'builtin.box.trap-alert.body-teal',
        },
      },
      {
        id: 'neutral',
        label: '中性',
        description: '切换为中性灰避坑框。',
        tokenBindings: {
          accentColor: 'builtin.box.trap-alert.accent-neutral',
          frameBorder: 'builtin.box.trap-alert.frame-neutral',
          headerFill: 'builtin.box.trap-alert.header-neutral',
          bodyFill: 'builtin.box.trap-alert.body-neutral',
        },
      },
    ],
  },
})
