import './styles.css'
import { defineBoxSkin } from '@/utils/teachingDocument/skins/authoring'

export default defineBoxSkin({
  id: 'builtin.box.left-accent',
  label: '左侧强调线',
  description: '使用左侧色带强调卡片内容。',
  version: 1,
  printSafe: true,
  className: 'td-skin-box-left-accent',
  tags: ['builtin', 'box'],
  design: {
    tokens: [
      { id: 'builtin.box.left-accent.border-blue', kind: 'color', label: '浅蓝边框', printSafe: true, value: { hex: '#BFDBFE' } },
      { id: 'builtin.box.left-accent.border-green', kind: 'color', label: '浅绿边框', printSafe: true, value: { hex: '#A7F3D0' } },
      { id: 'builtin.box.left-accent.border-amber', kind: 'color', label: '浅琥珀边框', printSafe: true, value: { hex: '#FDE68A' } },
      { id: 'builtin.box.left-accent.border-red', kind: 'color', label: '浅红边框', printSafe: true, value: { hex: '#FECACA' } },
      { id: 'builtin.box.left-accent.border-purple', kind: 'color', label: '浅紫边框', printSafe: true, value: { hex: '#DDD6FE' } },
      { id: 'builtin.box.left-accent.border-teal', kind: 'color', label: '浅青边框', printSafe: true, value: { hex: '#99F6E4' } },
      { id: 'builtin.box.left-accent.border-neutral', kind: 'color', label: '中性边框', printSafe: true, value: { hex: '#D4D4D8' } },
      { id: 'builtin.box.left-accent.accent-blue', kind: 'color', label: '蓝色强调线', printSafe: true, value: { hex: '#2563EB' } },
      { id: 'builtin.box.left-accent.accent-green', kind: 'color', label: '绿色强调线', printSafe: true, value: { hex: '#047857' } },
      { id: 'builtin.box.left-accent.accent-amber', kind: 'color', label: '琥珀强调线', printSafe: true, value: { hex: '#B45309' } },
      { id: 'builtin.box.left-accent.accent-red', kind: 'color', label: '红色强调线', printSafe: true, value: { hex: '#B91C1C' } },
      { id: 'builtin.box.left-accent.accent-purple', kind: 'color', label: '紫色强调线', printSafe: true, value: { hex: '#7C3AED' } },
      { id: 'builtin.box.left-accent.accent-teal', kind: 'color', label: '青色强调线', printSafe: true, value: { hex: '#0F766E' } },
      { id: 'builtin.box.left-accent.accent-neutral', kind: 'color', label: '中性强调线', printSafe: true, value: { hex: '#3F3F46' } },
      { id: 'builtin.box.left-accent.header-blue', kind: 'color', label: '浅蓝标题底色', printSafe: true, value: { hex: '#EFF6FF' } },
      { id: 'builtin.box.left-accent.header-green', kind: 'color', label: '浅绿标题底色', printSafe: true, value: { hex: '#ECFDF5' } },
      { id: 'builtin.box.left-accent.header-amber', kind: 'color', label: '浅琥珀标题底色', printSafe: true, value: { hex: '#FFFBEB' } },
      { id: 'builtin.box.left-accent.header-red', kind: 'color', label: '浅红标题底色', printSafe: true, value: { hex: '#FEF2F2' } },
      { id: 'builtin.box.left-accent.header-purple', kind: 'color', label: '浅紫标题底色', printSafe: true, value: { hex: '#F5F3FF' } },
      { id: 'builtin.box.left-accent.header-teal', kind: 'color', label: '浅青标题底色', printSafe: true, value: { hex: '#F0FDFA' } },
      { id: 'builtin.box.left-accent.header-neutral', kind: 'color', label: '中性标题底色', printSafe: true, value: { hex: '#F4F4F5' } },
      { id: 'builtin.box.left-accent.body-white', kind: 'color', label: '白色正文底色', printSafe: true, value: { hex: '#FFFFFF' } },
      { id: 'builtin.box.left-accent.frame-blue', kind: 'border', label: '浅蓝边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.left-accent.border-blue' } },
      { id: 'builtin.box.left-accent.frame-green', kind: 'border', label: '浅绿边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.left-accent.border-green' } },
      { id: 'builtin.box.left-accent.frame-amber', kind: 'border', label: '浅琥珀边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.left-accent.border-amber' } },
      { id: 'builtin.box.left-accent.frame-red', kind: 'border', label: '浅红边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.left-accent.border-red' } },
      { id: 'builtin.box.left-accent.frame-purple', kind: 'border', label: '浅紫边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.left-accent.border-purple' } },
      { id: 'builtin.box.left-accent.frame-teal', kind: 'border', label: '浅青边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.left-accent.border-teal' } },
      { id: 'builtin.box.left-accent.frame-neutral', kind: 'border', label: '中性边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.box.left-accent.border-neutral' } },
      { id: 'builtin.box.left-accent.accent-border-blue', kind: 'border', label: '蓝色强调线', printSafe: true, value: { widthPx: 4, style: 'solid', colorTokenId: 'builtin.box.left-accent.accent-blue' } },
      { id: 'builtin.box.left-accent.accent-border-green', kind: 'border', label: '绿色强调线', printSafe: true, value: { widthPx: 4, style: 'solid', colorTokenId: 'builtin.box.left-accent.accent-green' } },
      { id: 'builtin.box.left-accent.accent-border-amber', kind: 'border', label: '琥珀强调线', printSafe: true, value: { widthPx: 4, style: 'solid', colorTokenId: 'builtin.box.left-accent.accent-amber' } },
      { id: 'builtin.box.left-accent.accent-border-red', kind: 'border', label: '红色强调线', printSafe: true, value: { widthPx: 4, style: 'solid', colorTokenId: 'builtin.box.left-accent.accent-red' } },
      { id: 'builtin.box.left-accent.accent-border-purple', kind: 'border', label: '紫色强调线', printSafe: true, value: { widthPx: 4, style: 'solid', colorTokenId: 'builtin.box.left-accent.accent-purple' } },
      { id: 'builtin.box.left-accent.accent-border-teal', kind: 'border', label: '青色强调线', printSafe: true, value: { widthPx: 4, style: 'solid', colorTokenId: 'builtin.box.left-accent.accent-teal' } },
      { id: 'builtin.box.left-accent.accent-border-neutral', kind: 'border', label: '中性强调线', printSafe: true, value: { widthPx: 4, style: 'solid', colorTokenId: 'builtin.box.left-accent.accent-neutral' } },
      { id: 'builtin.box.left-accent.radius', kind: 'radius', label: '圆角', printSafe: true, value: { px: 4 } },
    ],
    slots: [
      {
        id: 'frameBorder',
        kind: 'border',
        defaultTokenId: 'builtin.box.left-accent.frame-blue',
        allowedTokenIds: [
          'builtin.box.left-accent.frame-blue',
          'builtin.box.left-accent.frame-green',
          'builtin.box.left-accent.frame-amber',
          'builtin.box.left-accent.frame-red',
          'builtin.box.left-accent.frame-purple',
          'builtin.box.left-accent.frame-teal',
          'builtin.box.left-accent.frame-neutral',
        ],
      },
      {
        id: 'accentBorder',
        kind: 'border',
        defaultTokenId: 'builtin.box.left-accent.accent-border-blue',
        allowedTokenIds: [
          'builtin.box.left-accent.accent-border-blue',
          'builtin.box.left-accent.accent-border-green',
          'builtin.box.left-accent.accent-border-amber',
          'builtin.box.left-accent.accent-border-red',
          'builtin.box.left-accent.accent-border-purple',
          'builtin.box.left-accent.accent-border-teal',
          'builtin.box.left-accent.accent-border-neutral',
        ],
      },
      {
        id: 'headerFill',
        kind: 'color',
        defaultTokenId: 'builtin.box.left-accent.header-blue',
        allowedTokenIds: [
          'builtin.box.left-accent.header-blue',
          'builtin.box.left-accent.header-green',
          'builtin.box.left-accent.header-amber',
          'builtin.box.left-accent.header-red',
          'builtin.box.left-accent.header-purple',
          'builtin.box.left-accent.header-teal',
          'builtin.box.left-accent.header-neutral',
        ],
      },
      { id: 'bodyFill', kind: 'color', defaultTokenId: 'builtin.box.left-accent.body-white' },
      { id: 'radius', kind: 'radius', defaultTokenId: 'builtin.box.left-accent.radius' },
    ],
    variants: [
      {
        id: 'green',
        label: '绿色',
        description: '将卡片切换为绿色强调色。',
        tokenBindings: { frameBorder: 'builtin.box.left-accent.frame-green', accentBorder: 'builtin.box.left-accent.accent-border-green', headerFill: 'builtin.box.left-accent.header-green' },
      },
      {
        id: 'amber',
        label: '琥珀',
        description: '将卡片切换为琥珀强调色。',
        tokenBindings: { frameBorder: 'builtin.box.left-accent.frame-amber', accentBorder: 'builtin.box.left-accent.accent-border-amber', headerFill: 'builtin.box.left-accent.header-amber' },
      },
      {
        id: 'red',
        label: '红色',
        description: '将卡片切换为红色强调色。',
        tokenBindings: { frameBorder: 'builtin.box.left-accent.frame-red', accentBorder: 'builtin.box.left-accent.accent-border-red', headerFill: 'builtin.box.left-accent.header-red' },
      },
      {
        id: 'purple',
        label: '紫色',
        description: '将卡片切换为紫色强调色。',
        tokenBindings: { frameBorder: 'builtin.box.left-accent.frame-purple', accentBorder: 'builtin.box.left-accent.accent-border-purple', headerFill: 'builtin.box.left-accent.header-purple' },
      },
      {
        id: 'teal',
        label: '青色',
        description: '将卡片切换为青色强调色。',
        tokenBindings: { frameBorder: 'builtin.box.left-accent.frame-teal', accentBorder: 'builtin.box.left-accent.accent-border-teal', headerFill: 'builtin.box.left-accent.header-teal' },
      },
      {
        id: 'neutral',
        label: '中性',
        description: '将卡片切换为中性灰强调色。',
        tokenBindings: { frameBorder: 'builtin.box.left-accent.frame-neutral', accentBorder: 'builtin.box.left-accent.accent-border-neutral', headerFill: 'builtin.box.left-accent.header-neutral' },
      },
    ],
  },
})
