import './styles.css'
import { defineHeadingSkin } from '@/utils/teachingDocument/skins/authoring'

export default defineHeadingSkin({
  id: 'builtin.heading.pill',
  label: '圆角标签标题',
  description: '带低对比圆角底色的章节标题。',
  version: 1,
  printSafe: true,
  className: 'td-skin-heading-pill',
  supportedLevels: [1, 2, 3, 4],
  tags: ['builtin', 'heading'],
  design: {
    tokens: [
      { id: 'builtin.heading.pill.fill-blue', kind: 'color', label: '浅蓝底色', printSafe: true, value: { hex: '#EFF6FF' } },
      { id: 'builtin.heading.pill.fill-green', kind: 'color', label: '浅绿底色', printSafe: true, value: { hex: '#ECFDF5' } },
      { id: 'builtin.heading.pill.fill-amber', kind: 'color', label: '浅琥珀底色', printSafe: true, value: { hex: '#FFFBEB' } },
      { id: 'builtin.heading.pill.fill-red', kind: 'color', label: '浅红底色', printSafe: true, value: { hex: '#FEF2F2' } },
      { id: 'builtin.heading.pill.fill-purple', kind: 'color', label: '浅紫底色', printSafe: true, value: { hex: '#F5F3FF' } },
      { id: 'builtin.heading.pill.fill-teal', kind: 'color', label: '浅青底色', printSafe: true, value: { hex: '#F0FDFA' } },
      { id: 'builtin.heading.pill.fill-neutral', kind: 'color', label: '中性底色', printSafe: true, value: { hex: '#F4F4F5' } },
      { id: 'builtin.heading.pill.border-blue', kind: 'color', label: '浅蓝边框', printSafe: true, value: { hex: '#BFDBFE' } },
      { id: 'builtin.heading.pill.border-green', kind: 'color', label: '浅绿边框', printSafe: true, value: { hex: '#A7F3D0' } },
      { id: 'builtin.heading.pill.border-amber', kind: 'color', label: '浅琥珀边框', printSafe: true, value: { hex: '#FDE68A' } },
      { id: 'builtin.heading.pill.border-red', kind: 'color', label: '浅红边框', printSafe: true, value: { hex: '#FECACA' } },
      { id: 'builtin.heading.pill.border-purple', kind: 'color', label: '浅紫边框', printSafe: true, value: { hex: '#DDD6FE' } },
      { id: 'builtin.heading.pill.border-teal', kind: 'color', label: '浅青边框', printSafe: true, value: { hex: '#99F6E4' } },
      { id: 'builtin.heading.pill.border-neutral', kind: 'color', label: '中性边框', printSafe: true, value: { hex: '#D4D4D8' } },
      { id: 'builtin.heading.pill.frame-blue', kind: 'border', label: '浅蓝边框边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.heading.pill.border-blue' } },
      { id: 'builtin.heading.pill.frame-green', kind: 'border', label: '浅绿边框边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.heading.pill.border-green' } },
      { id: 'builtin.heading.pill.frame-amber', kind: 'border', label: '浅琥珀边框边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.heading.pill.border-amber' } },
      { id: 'builtin.heading.pill.frame-red', kind: 'border', label: '浅红边框边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.heading.pill.border-red' } },
      { id: 'builtin.heading.pill.frame-purple', kind: 'border', label: '浅紫边框边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.heading.pill.border-purple' } },
      { id: 'builtin.heading.pill.frame-teal', kind: 'border', label: '浅青边框边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.heading.pill.border-teal' } },
      { id: 'builtin.heading.pill.frame-neutral', kind: 'border', label: '中性边框边框', printSafe: true, value: { widthPx: 1, style: 'solid', colorTokenId: 'builtin.heading.pill.border-neutral' } },
    ],
    slots: [
      {
        id: 'pillFill',
        kind: 'color',
        defaultTokenId: 'builtin.heading.pill.fill-neutral',
        allowedTokenIds: [
          'builtin.heading.pill.fill-blue',
          'builtin.heading.pill.fill-green',
          'builtin.heading.pill.fill-amber',
          'builtin.heading.pill.fill-red',
          'builtin.heading.pill.fill-purple',
          'builtin.heading.pill.fill-teal',
          'builtin.heading.pill.fill-neutral',
        ],
      },
      {
        id: 'pillBorder',
        kind: 'border',
        defaultTokenId: 'builtin.heading.pill.frame-neutral',
        allowedTokenIds: [
          'builtin.heading.pill.frame-blue',
          'builtin.heading.pill.frame-green',
          'builtin.heading.pill.frame-amber',
          'builtin.heading.pill.frame-red',
          'builtin.heading.pill.frame-purple',
          'builtin.heading.pill.frame-teal',
          'builtin.heading.pill.frame-neutral',
        ],
      },
    ],
    variants: [
      {
        id: 'blue',
        label: '蓝色',
        description: '将标签标题切换为蓝色系。',
        tokenBindings: { pillFill: 'builtin.heading.pill.fill-blue', pillBorder: 'builtin.heading.pill.frame-blue' },
      },
      {
        id: 'green',
        label: '绿色',
        description: '将标签标题切换为绿色系。',
        tokenBindings: { pillFill: 'builtin.heading.pill.fill-green', pillBorder: 'builtin.heading.pill.frame-green' },
      },
      {
        id: 'amber',
        label: '琥珀',
        description: '将标签标题切换为琥珀色系。',
        tokenBindings: { pillFill: 'builtin.heading.pill.fill-amber', pillBorder: 'builtin.heading.pill.frame-amber' },
      },
      {
        id: 'red',
        label: '红色',
        description: '将标签标题切换为红色系。',
        tokenBindings: { pillFill: 'builtin.heading.pill.fill-red', pillBorder: 'builtin.heading.pill.frame-red' },
      },
      {
        id: 'purple',
        label: '紫色',
        description: '将标签标题切换为紫色系。',
        tokenBindings: { pillFill: 'builtin.heading.pill.fill-purple', pillBorder: 'builtin.heading.pill.frame-purple' },
      },
      {
        id: 'teal',
        label: '青色',
        description: '将标签标题切换为青色系。',
        tokenBindings: { pillFill: 'builtin.heading.pill.fill-teal', pillBorder: 'builtin.heading.pill.frame-teal' },
      },
      {
        id: 'neutral',
        label: '中性',
        description: '显式选择中性灰标签（与 Base 一致）。',
        tokenBindings: { pillFill: 'builtin.heading.pill.fill-neutral', pillBorder: 'builtin.heading.pill.frame-neutral' },
      },
    ],
  },
})
